services:
  nginx:
    build: ./requirements/nginx
    container_name: inception-nginx
    image: nginx
    depends_on:
      - wordpress
#    restart: unless-stopped
  
  wordpress:
    build: ./requirements/wordpress
    container_name: inception-wordpress
    image: wordpress
    depends_on:
      - mariadb
#    restart: unless-stopped
  
  mariadb:
    build: ./requirements/mariadb
    container_name: inception-mariadb
    image: mariadb

networks:
  inception-net:
    name: main-net
    driver: bridge
