#### CONF FOR MARIADB SERVER ####
[mysqld]
user = mysql

# Allow conections from other containers
bind-address = 0.0.0.0
port = 3306

# The path to the containers data dir
datadir = /var/lib/mysql
socket = /run/mysqld/mysqld.sock

# Is not connected to web
skip-networking = 0
